# This is the configuration used to check the rubocop source code.

# inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - Gemfile
  TargetRubyVersion: 2.1

Documentation:
  Enabled: false
Style/SymbolProc:
  IgnoredMethods:
    - configure
Style/ClassAndModuleChildren:
  Enabled: false
